# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: loginapi
    build: .
    command: gunicorn -b 0.0.0.0:5000 loginapi.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=mysql://root:root@database/loginapi
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=amqp://guest:guest@rabbitmq
    volumes:
      - ./loginapi:/code/loginapi
      - ./db/:/db/
    ports:
      - "5000:5000"
    links:
      - "mysql:database"
    depends_on:
      - redis
      - mysql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis
  celery:
    image: loginapi
    build: .
#    command: "celery worker -A loginapi.celery_app:app"
    command: "celery -A celery_app worker"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
