"""Drop column user.email

Revision ID: 28db89648641
Revises: 09e9ac236ac7
Create Date: 2020-10-05 20:53:14.599292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28db89648641'
down_revision = '09e9ac236ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=80), nullable=False))
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
